# custom unique constants for errors
INVALID_CODE = 1
NAME_ALREADY_TAKEN = 2
WRONG_PAYLOAD_LENGTH = 3
WRONG_PAYLOAD_SIZE_FIELD = 4
DATABASE_ERROR = 5
INVALID_CLIENT_VERSION = 6
CLIENT_NOT_IN_DATABASE = 7
INVALID_MESSAGE_TYPE = 8
INVALID_MESSAGE_CONTENT_SIZE = 9
ERROR_ADDING_CLIENT = 11
TOO_LITTLE_PACKAGE_ARRIVED = 12
SQL_GENERAL_ERROR = -1
POSSIBLE_INJECTION = -2

# positions in the full header
HEADER_CLIENT_ID_POSITION = 0
HEADER_SERVER_VERSION_POSITION = 1
HEADER_CODE_POSITION = 2
HEADER_PAYLOAD_SIZE_FIELD_POSITION = 3

# positions in the received buffer
PAYLOAD_START_POSITION = 22

# important lengths
NAME_LENGTH = 255
PUBLIC_KEY_LENGTH = 160
SYMMETRIC_KEY_LENGTH = 16
FULL_HEADER_LENGTH = 22
SEND_MESSAGE_HEADER_LENGTH = 21
RECEIVE_MESSAGE_HEADER_LENGTH = 25
MESSAGE_ID_LENGTH = 4
CLIENT_ID_LENGTH = 16
EMPTY_PAYLOAD_LENGTH = 0

# miscellaneous constants
CLIENT_VERSION = 1
SERVER_VERSION = 2
CLIENTS_ARRAY_POSITION = 3
MESSAGES_ARRAY_POSITION = 3
CLIENT_ADDED_SUCCESSFULLY = 4

# constants for request codes
CODE_FOR_REGISTER = 100
CODE_FOR_GET_ALL_CLIENTS = 101
CODE_FOR_GET_PUBLIC_KEY = 102
CODE_FOR_SENDING_MESSAGE = 103
CODE_FOR_PULLING_MESSAGES = 104

# messages types
ASK_SYMMETRIC_KEY_TYPE = 1
SEND_SYMMETRIC_KEY_TYPE = 2
SEND_TEXT_MESSAGE_TYPE = 3

# constants for response constants
RESPONSE_GENERAL_ERROR = 9000
RESPONSE_REGISTER_SUCCESS = 1000
RESPONSE_GET_CLIENTS_SUCCESS = 1001
RESPONSE_GET_PUBLIC_KEY_SUCCESS = 1002
RESPONSE_SENDING_MESSAGE_SUCCESS = 1003
RESPONSE_PULLING_MESSAGES_SUCCESS = 1004
PROCESSING_BIG_TEXT_MESSAGE = 2000

DEBUG_MODE = True
